set(VERSION_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/include/generated")

set(RELEASE_AUTHOR "Johnny Mast")
set(RELEASE_VERSION_MAJOR 0)
set(RELEASE_VERSION_MINOR 10)
set(RELEASE_VERSION_PATCH 0)
set(RELEASE_VERSION_TYPE "alpha")
set(RELEASE_YEAR 2026)
set(RELEASE_VERSION_STRING "${RELEASE_VERSION_MAJOR}.${RELEASE_VERSION_MINOR}.${RELEASE_VERSION_PATCH} ${RELEASE_VERSION_TYPE}")

file(MAKE_DIRECTORY ${VERSION_HEADER_DIR})
configure_file(
        "${CMAKE_CURRENT_SOURCE_DIR}/config/version.hpp.in"
        "${VERSION_HEADER_DIR}/version.hpp"
        @ONLY
)