name: Build

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      TESSDATA_PREFIX: /usr/share/tesseract-ocr/5/tessdata

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential pkg-config libopencv-dev libleptonica-dev tesseract-ocr libtesseract-dev

      - name: Finding TESSDATA_PREFIX
        run: |
          export TESSDATA_PREFIX=$(find /usr/share -type d -name tessdata | head -n 1)
          echo "TESSDATA_PREFIX=$TESSDATA_PREFIX" >> $GITHUB_ENV

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --config Release -- -j$(nproc)
